### ISSUE TITLE
Attempted Daemonset weave-tc, but DNS requests flatlined

### ISSUE THREAD

**Issue by chrisghill** [Quentin-M/weave-tc#7]
So I think I've been experiencing these DNS timeouts for a couple of months now, and I decided to try your patch as it seemed the least invasive first step (and maybe last step) at fixing the issue.  I didn't want to modify the weave-net daemonset since it is core to kubernetes so I decided to create a separate "weave-tc" daemonset that did the same thing.  Here is the manifest:

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    name: weave-tc
    role.kubernetes.io/networking: "1"
  name: weave-tc
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        name: weave-tc
        role.kubernetes.io/networking: "1"      
    spec:
      containers:
      - name: weave-tc
        image: 'qmachu/weave-tc:bd94b89'
        securityContext:
          privileged: true
        volumeMounts:
        - name: xtables-lock
          mountPath: /run/xtables.lock
        - name: lib-tc
          mountPath: /lib/tc
      hostNetwork: true
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      volumes:
      - hostPath:
          path: /usr/lib/tc
          type: Directory
        name: lib-tc
      - hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
        name: xtables-lock
```

I actually attempted this first in a test kubernetes cluster and it seemed to work fine.  I tried it in our main cluster and network traffic immediately started failing.  Services started responding extremely slowly (or not at all).  Here is a picture of our CoreDNS metrics:

![image](https://user-images.githubusercontent.com/15616541/57744037-cbe42d00-7684-11e9-9035-76c237413d51.png)

I didn't spend much time digging into what went wrong, I just quickly did a rolling update of the cluster to undo the changes.  I though I'd post it here in case you had any idea what could have gone wrong.  I'd still prefer to use your solution over a node-local-dns configuration, but I'm a but hesitant after the last attempt.

In terms of our cluster, we're running kubernetes 1.11.9, deployed via Kops, network is weave-net and DNS is CoreDNS.  Please let me know if you need any other details.

Also, I pulled the logs from our logging cluster (pods were already deleted), but here it is:

```
+ NET_OVERLAY_IF=weave
+ DNSMASQ_PORT=53
+ sysctl -w net.core.default_qdisc=fq_codel
+ grep -o [^ ]*$
+ grep ^default
net.core.default_qdisc = fq_codel
+ route
+ tc qdisc del dev eth0 root
+ true
+ grep ^default
+ route
+ tc qdisc add dev eth0 root handle 0: mq
+ grep -o [^ ]*$
+ grep weave
+ ip link
+ tc qdisc del dev weave root
+ tc qdisc add dev weave root handle 1: prio bands 2 priomap 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
+ true
+ tc qdisc add dev weave parent 1:2 handle 12: fq_codel
+ tc qdisc add dev weave parent 1:1 handle 11: netem delay 4ms 1ms distribution pareto
+ tc filter add dev weave protocol all parent 1: prio 1 handle 0x100/0x100 fw flowid 1:1
+ iptables -A POSTROUTING -t mangle -p udp --dport 53 -m string -m u32 --u32 28 & 0xF8 = 0 --hex-string |00001C0001| --algo bm --from 40 -j MARK --set-mark 0x100/0x100
+ sleep 3600
```

**Comment by Quentin-M** [comment]
Hi~

I am so sorry to hear about your experience.. Nothing looks out of ordinary on those execution logs. The fact that you lost most of your network connectivity makes me feel like your operating system may not have the same default tc setup? Is there a difference between your test/prod clusters (operating system, kernel version, modules, ...)? 

We are running in CoreOS Container Linux in production, so only tested there. It's been a long time I worked on this as everything is smooth now, but I can take a look. Would you be able to dump the result of `tc qdisc show dev weave` before running the script?

The first two tc operations can be skipped, they are just in place to improve default tc policy on the default interface, and actually have nothing to do with the fix. The other three tc operations should have *no* impact whatsoever on the traffic passing through your overlay network interface - until you run the iptables command, which will start marking matching packets. If the three tc operations are enough to cause trouble, then something is messed up.

**Comment by chrisghill** [comment]
Thanks for your response.

We're running kops, so we're using the kops AMI's in AWS, which are debian stretch.  Perhaps that has something to do with it?

I hopped on a node and ran `tc qdisc show dev weave` and got:

```
root@ip-172-20-69-17:~# tc qdisc show dev weave
qdisc noqueue 0: root refcnt 2
```

I also went ahead and made a small container just like yours except the script only runs that `tc` command (in case running in a container against a host network is different than running against the node itself), but the response was the same:

```
+ tc qdisc show dev weave
qdisc noqueue 0: root refcnt 2 
+ sleep 3600
```

Edit: I should note that I **did not** mount the `tc` binary from the node in my daemonset above. I used the tc binary that was native to the image.  But I did mount the `xlock` and `/lib/tc` directories.

**Comment by chrisghill** [comment]
More info - I kinda tried this again by running your script against some of the nodes themselves (raw script, not in any containers or daemonsets).  Thus far I've seen timeouts disappear, and network traffic is stable.  I'm wondering if the issue was that I didn't mount the `tc` binary.  That would have caused me to run the alpine `tc` binary against a debian linux.  Maybe that causes an issue?

**Comment by Quentin-M** [comment]
So fantastic to hear @chrisghill!
The output for `qdisc show dev weave` before running the script does look okay.
Re: tc - Maaybe?

**Comment by chrisghill** [comment]
Yeah, I ended up making my own docker container based off of debian and using that in the daemonset with no changes to your script.  I've seen timeouts completely disappear.

It's certainly possible that there was something else wrong with the config when I tried your Alpine container, but for now we're going to run with this debian version.  Here is the Dockerfile for anyone interested:

```
FROM debian:stretch
RUN apt-get update && apt-get install iproute2 && apt-get install --yes procps && apt-get install --yes iptables && apt-get install --yes net-tools
ENV DNSMASQ_PORT=53
ENV NET_OVERLAY_IF=weave
ADD . .
ENTRYPOINT ./weave-tc.sh
```

And the Daemonset config:
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    name: weave-tc
    role.kubernetes.io/networking: "1"
  name: weave-tc
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        name: weave-tc
        role.kubernetes.io/networking: "1"
    spec:
      containers:
      - name: weave-tc
        image: <image>
        securityContext:
          privileged: true
        volumeMounts:
        - name: xtables-lock
          mountPath: /run/xtables.lock
        - name: lib-tc
          mountPath: /usr/lib/tc
      hostNetwork: true
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      volumes:
      - hostPath:
          path: /usr/lib/tc
          type: Directory
        name: lib-tc
      - hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
        name: xtables-lock
```

Thanks for all your help in investigating and creating this conntrack patch @Quentin-M .
